### ISSUE TITLE
Thanks for open sourcing it!

### ISSUE THREAD

**Issue by nikgraf** [szdavid92/joi-extension-semver#1]
Just a shout out. Was helpful to find it on Github 👏

**Comment by nikgraf** [comment]
One suggestion after I read the code: Add a license so someone can use your software without getting into legal trouble.

**Comment by szdavid92** [comment]
Hi! Thanks for the heads up, totally forgot to add the license. I guess MIT will do it.

**Comment by szdavid92** [comment]
Done! Thanks for using the library!
